baseURL = 'https://hugo-home-page.netlify.app/'
languageCode = 'en-us'
title = 'Anubis'
theme = "anubis"
paginate = 3

[menu]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/"
weight = 3

[[menu.main]]
name = "Contact"
identifier = "contact"
url = "/about/"
weight = 6

[[menu.main]]
name = "Support"
identifier = "support"
url = "/"
weight = 4

[[menu.main]]
name = "Service"
identifier = "service"
url = "/about/"
weight = 5

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true

